server:
  port: 8079 # 服务端口

spring:
  application:
    name: lab-41-demo04 # 应用名
  metrics:
    servo:
      enabled: false # 只展示 spring boot 和自己项目吐出的 metrics 了，默认在微服务中 Spring Cloud 因 Metrics 采集数据剧增导致CPU负载过高

management:
  security:
    enabled: false # 1.5x 版本暴露所有端点
  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

  metrics:
    tags: # 通用标签
      application: ${spring.application.name}

