server:
  port: 8079
  address: 0.0.0.0

management:
  server:
    port: 8078 # 自定义端口，避免 Nginx 暴露出去

  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
