spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 192.168.177.4 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: mqadmin # RabbitMQ 服务的账号
    password: mqadmin # RabbitMQ 服务的密码
    publisher-confirm-type: correlated # 设置 Confirm 类型为 CORRELATED 。
    publisher-returns: true #
