spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 192.168.177.4 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: mqadmin # RabbitMQ 服务的账号
    password: mqadmin # RabbitMQ 服务的密码
    listener:
      type: simple # 选择的 MessageListenerContainer 的类型。默认为 direct 类型
      simple:
        concurrency: 2 # 每个 @ListenerContainer 的并发消费的线程数
        max-concurrency: 10 # 每个 @ListenerCon 允许的并发消费的线程数
#      direct:
#        consumers-per-queue: 2 # 对于每一个 @RabbitListener ，一个 Queue ，对应创建几个 Consumer 。
