# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  name-server: http://MQ_INST_1702037966651832_BXrrVt4h.mq-internet-access.mq-internet.aliyuncs.com:80 # 阿里云 RocketMQ Namesrv
  # 阿里云 RocketMQ Namesrv
  access-channel: CLOUD # 设置使用阿里云
  # Producer 配置项
  producer:
    sendMessageTimeout: 6000 # 踩坑：设置超时时间，因为使用的是阿里云RocketMq
    group: GID_PRODUCER_GROUP_JAQUEZ_TEST # 生产者分组
    access-key:  # 设置阿里云的 RocketMQ 的 access key ！！！这里涉及到隐私，所以这里艿艿没有提供
    secret-key:  # 设置阿里云的 RocketMQ 的 secret key ！！！这里涉及到隐私，所以这里艿艿没有提供