# xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8888/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      # Xxl-job-plus 新增配置项，必须项
      username: jaquez
      password: 123456
    executor:
      appname: lab-28-executor-plus # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: C:/MyData/Project/SpringBoot-Labs/lab-28/lab-28-task-xxl-job/logs/xxl-job/lab-28-executor # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      # Xxl-job-plus 新增配置项，必须项
      title: lab_28_升级
      # Xxl-job-plus 新增配置项，可选项
      addressType: 1 # 执行器地址类型：0=自动注册、1=手动录入，默认为0
      addressList: http://192.168.177.3:6666,http://192.168.10.37:6666,http://127.0.0.1:6666
    accessToken: # 执行器通讯TOKEN [选填]：非空时启用；
