spring:
  application:
    name: demo-application-elasticsearch # 应用名称

  data:
    # Elasticsearch 配置项
    elasticsearch:
      cluster-name: elasticsearch # 集群名
      cluster-nodes: 192.168.177.4:9300 # 集群节点
