spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: 1f5b16d5-5ecd-42b9-ba01-482ff407dc9c # Nacos 命名空间 uat 的编号
