spring:
  data:
    # Jest 配置项
    jest:
      uri: http://192.168.177.4:9200

# 日志
logging:
  level:
    cn:
      iocoder:
        springboot:
          lab15:
            springdatajest:
              repository: DEBUG