spring:
  application:
    name: publisher-demo # 应用名称

  # RabbitMQ 相关配置项
  rabbitmq:
    host: 192.168.177.4
    port: 5672
    username: mqadmin
    password: mqadmin

  # Bus 相关配置项，对应 BusProperties
  cloud:
    bus:
      enabled: true # 是否开启，默认为 true
      destination: springCloudBus # 目标消息队列，默认为 springCloudBus
