#基础镜像
FROM java:8-jre

#项目挂载的/opt/docker/file/目录，踩坑：这里只能设置容器挂载目录，宿主机目录设置不了
VOLUME /opt/docker/file/

#踩坑：相对于Dockerfile位置路径，windows 路径不识别
ENV FILE_ROOT_PATH ./
COPY $FILE_ROOT_PATH/target/lib ./lib/

#将项目的jar包拷贝并命名
ADD $FILE_ROOT_PATH/target/lab-72-docker-demo-2.jar app.jar

ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8

RUN bash -c 'touch /app.jar'

#暴露端口
EXPOSE 8079 8078

#ENV JAVA_OPTS="-Duser.timezone=Asia/Shanghai"
ENV APP_OPTS="--spring.profiles.active=dev"

#设置时间，踩坑：这里的 \，注意结尾不能添加 \，\是拼接的意思
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo 'Asia/Shanghai' >/etc/timezone

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar $APP_OPTS" ]