spring:
  mail: # 配置发送告警的邮箱
    host: smtp.qq.com
    port: 465
    username: 643582433@qq.com
    password: bjmgokaxretkbdhi
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  boot:
    admin:
      notify:
        mail:
          from: ${spring.mail.username} # 告警发件人
          to: 2317774857@qq.com # 告警收件人
