server:
  port: 8081 # 服务端口

spring:
  application:
    name: publisher-demo # 应用名称

  cloud:
    # Consul
    consul:
      host: 192.168.177.4
      port: 8500
    # Bus 相关配置项，对应 BusProperties
    bus:
      enabled: true # 是否开启，默认为 true
      destination: springCloudBus # 目标消息队列，默认为 springCloudBus
