spring:
  application:
    name: listener-demo # 应用名称

server:
  port: ${random.int[10000,19999]} # 随机端口，方便启动多个消费者

# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  name-server: 192.168.177.4:9876 # RocketMQ Namesrv
