spring:
  application:
    name: demo-admin-server # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。

  mail: # 配置发送告警的邮箱
    host: smtp.163.com
    username: lzgd_warning@163.com
    password: 'AGPJJTKWSMHBWQCA'
    default-encoding: UTF-8

  boot:
    admin:
      notify:
        mail:
          from: ${spring.mail.username} # 告警发件人
          to: 2317774857@qq.com # 告警收件人
