spring:
  application:
    name: demo-application # 应用名

  output:
    ansi:
      enabled:logging: DETECT # 颜色配置，ALWAYS、NEVER、DETECT，默认 DETECT
  # 日志文件配置
  file:
#    path: /Users/yunai/logs/ # 日志文件路径。与下面配置二选一，在此目录下创建 spring.log 日志文件
    name: /Users/yunai/logs/${spring.application.name}.log # 日志文件名。
    max-history: 7 # 日志文件要保留的归档的最大天数。默认为 7 天。
    max-size: 10MB # 日志文件的最大大小。默认为 10MB 。

  # 日志级别
  level:
    cn:
      iocoder:
        springboot:
          lab37:
            loggingdemo:
              controller: DEBUG # TRACE、DEBUG、INFO、WARN、ERROR、FATAL、OFF


