server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lab-01-springsecurity
    username: root
    password: 123456

# token 配置
token:
  expiration-seconds: 300
  salt: _secret

